sdfghjkl;

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,6 @@
-name: "Build iOS app"
+name: "Build and Distribute iOS App"
 
 on:
-  # manual trigger but change to any supported event
   workflow_dispatch:
     branches: "*"
 
@@ -22,35 +21,26 @@ jobs:
           BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
           KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
         run: |
-          # create variables
           CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
           PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
           KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
 
-          # import certificate and provisioning profile from secrets
           echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
           echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
 
-          # create temporary keychain
           security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
           security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
           security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-
-          # import certificate to keychain
           security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
-          security list-keychain -d user -s $KEYCHAIN_PATH`
-
-          # apply provisioning profile
+          security list-keychain -d user -s $KEYCHAIN_PATH
           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
           cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
 
       - name: build archive
         run: |
           xcodebuild -scheme "IBHGithubAction" \
-          -workspace "IBHGithubAction.xcworkspace" \
           -archivePath $RUNNER_TEMP/IBHGithubAction.xcarchive \
           -sdk iphoneos \
-          -allowProvisioningUpdates \
           -configuration Debug \
           -destination generic/platform=iOS \
           clean archive
@@ -63,9 +53,18 @@ jobs:
           echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
           xcodebuild -exportArchive -archivePath $RUNNER_TEMP/IBHGithubAction.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build
 
-      - name: Upload application
+      - name: Verify if IPA file exists
+        run: |
+          if [ -f "$RUNNER_TEMP/build/IBHGithubAction.ipa" ]; then
+            echo "IPA file exists"
+          else
+            echo "IPA file not found"
+            exit 1
+          fi
+
+      - name: Upload application as artifact
         uses: actions/upload-artifact@v3
         with:
           name: app
-          path: ${{ runner.temp }}/build/IBHGithubAction.ipa
+          path: $RUNNER_TEMP/build/IBHGithubAction.ipa
           retention-days: 3
