updated yml file

diff --git a/.github/workflows/distribution_build_beta_testing.yml b/.github/workflows/distribution_build_beta_testing.yml
--- a/.github/workflows/distribution_build_beta_testing.yml
+++ b/.github/workflows/distribution_build_beta_testing.yml
@@ -18,23 +18,6 @@ jobs:
         run: |
           rm -rf ~/Library/Developer/Xcode/DerivedData
 
-      - name: Run Unit Tests on iPad 10th Generation (Rosetta)
-        run: |
-          sudo softwareupdate --install-rosetta --agree-to-license
-          xcodebuild test \
-          -workspace "IBHGithubAction.xcworkspace" \
-          -sdk iphonesimulator \
-          -destination generic/platform=iOS \
-          -resultBundlePath $RUNNER_TEMP/test-results \
-          -verbose | xcpretty
-
-      - name: Upload test results as artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results
-          path: ${{ runner.temp }}/test-results
-          retention-days: 3
-
       - name: Install the Apple certificate and provisioning profile
         env:
           BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
@@ -61,12 +44,46 @@ jobs:
         run: |
           xcodebuild -workspace "IBHGithubAction.xcworkspace" \
           -scheme "IBHGithubAction" \
-          -archivePath $RUNNER_TEMP/IBHGithubAction.xcarchive \
+          -archivePath $RUNNER_TEMP/ibhgithubaction.xcarchive \
           -sdk iphoneos \
           -configuration Release \
           -destination generic/platform=iOS \
+          -allowProvisioningUpdates \
           clean archive \
-          -verbose | tee xcodebuild.log | xcpretty
+          -verbose 2>&1 | tee $RUNNER_TEMP/xcodebuild.log | xcpretty
+
+      - name: List contents of $RUNNER_TEMP
+        run: |
+          echo "Listing contents of $RUNNER_TEMP:"
+          ls -la $RUNNER_TEMP
+
+      - name: Output xcodebuild.log contents
+        run: |
+          if [ -f "$RUNNER_TEMP/xcodebuild.log" ]; then
+            echo "----- xcodebuild.log -----"
+            cat "$RUNNER_TEMP/xcodebuild.log"
+            echo "----- End of xcodebuild.log -----"
+          else
+            echo "xcodebuild.log not found."
+          fi
+
+      - name: Check if xcodebuild.log exists
+        run: |
+          ls -la $RUNNER_TEMP
+          if [ -f "$RUNNER_TEMP/xcodebuild.log" ]; then
+            echo "xcodebuild.log found"
+            cat $RUNNER_TEMP/xcodebuild.log
+          else
+            echo "xcodebuild.log not found"
+            exit 1
+          fi
+
+      - name: Upload xcodebuild logs as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: xcodebuild-log
+          path: ${{ runner.temp }}/xcodebuild.log
+          retention-days: 3
 
       - name: Export ipa
         env:
@@ -74,7 +91,7 @@ jobs:
         run: |
           EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
           echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
-          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/IBHGithubAction.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build
+          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/ibhgithubaction.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build
 
       - name: Verify if IPA file exists
         run: |
